---
- name: Validate distribution and role variables
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate/validate.yml"
  tags: nginx_validate

- name: Set up prerequisites
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/prerequisites/prerequisites.yml"
  when: nginx_state != 'absent'
  tags: nginx_prerequisites

- name: "{{ nginx_setup | capitalize }} NGINX"
  when: nginx_enable | bool
  tags: nginx_enable
  block:
    - name: "{{ nginx_setup | capitalize }} NGINX Open Source"
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/opensource/install-oss.yml"
      when: nginx_type == 'opensource'
      tags: nginx_install_oss

    - name: Modify systemd parameters
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/config/modify-systemd.yml"
      when:
        - ansible_facts['service_mgr'] == 'systemd'
        - nginx_service_modify | bool
      tags: nginx_modify_systemd

- name: Trigger handlers if necessary
  ansible.builtin.meta: flush_handlers

- name: Configure logrotate for NGINX
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/config/setup-logrotate.yml"
  when:
    - nginx_logrotate_conf_enable | bool
    - nginx_state != 'absent'
  tags: nginx_logrotate_config
